### ISSUE TITLE
error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused？

### ISSUE THREAD

**Issue by opvexe** [nsqio/go-nsq#349]
the nsq service is deployed on the public network. (106.75.49.135:4161, 106.75.49.135:4150),Can send and receive messages normally, but there will be 'error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused? '

- docker-compose :

````
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command:  /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4151"
      - "4150:4150"
````

- Error message:

```
2/10/12 11:21:15 INF    1 [Study/Chegg] (nsqd:4150) connecting to nsqd
2022/10/12 11:21:15 ERR    1 [Study/Chegg] (nsqd:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
{"Address":["106.75.49.141:4150"],"level":"info","msg":"Receiving NSQ messages from addresses","time":"2022-10-12T11:21:15+08:00"}
```

send message:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/26895243/195242874-d58d4aa6-ea61-45ad-8a5e-d08ba41b5889.png">

sub message:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/26895243/195242901-89a3d372-0d29-482e-8338-255183bedb5d.png">
